feature: animation triggers and optional header tip rendering
nomi9995/react-native-bottomsheet-reanimated pull request #5
Opened 2021-01-12 19:55 UTC by gorda0

2021-01-18 11:16 UTC, nomi9995 commented on example/src/App.js
> +    this.sheetRef.current.snapTo(index);
here app is crashing. without `current` it is working good

2021-01-18 11:17 UTC, nomi9995 commented on src/index.js
> +    this._deltaY = new Animated.Value(500);
can you elaborate on why you gave 500 static value?

2021-01-18 11:22 UTC, nomi9995 commented on src/index.js
> +      renderTip = true,
`isRoundBorderWithTipHeader` props is already available for `renderTip` therefore, no need to add `renderTip` props

2021-01-18 11:22 UTC, nomi9995 commented on src/index.js
> +            {!isModal && isRoundBorderWithTipHeader && renderTip && (
there is no need for `renderTip`

2021-01-18 11:22 UTC, nomi9995 commented on src/index.js
> +              renderTip && [
there is no need for `renderTip`

2021-01-18 11:23 UTC, nomi9995 requested changes
Thanks. there is no need for `renderTip` because `isRoundBorderWithTipHeader` this props already exist for this purpose

2021-01-21 22:02 UTC, gorda0 commented on src/index.js
> +    this._deltaY = new Animated.Value(500);
Just a test mistake.

2021-01-21 22:02 UTC, gorda0 commented on example/src/App.js
> +    this.sheetRef.current.snapTo(index);
fixed!

2021-05-10 22:32 UTC, closed without merging